name: Multi Job Workflow

on: push

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello Jagadeesh"

      - name: Show Date
        run: date

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Show System Info
        run: uname -a

      - name: List Files
        run: ls -la
